# Generated by Django 5.2.1 on 2025-05-17 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_ages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='has_child',
        ),
        migrations.AlterField(
            model_name='client',
            name='ages',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, default='media/rooms/default.jpeg', null=True, upload_to='media/rooms/', verbose_name='Фото номера'),
        ),
    ]
