# Generated by Django 5.2.1 on 2025-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_client_has_child_alter_client_ages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, default='/rooms/default.jpeg', null=True, upload_to='media/rooms/', verbose_name='Фото номера'),
        ),
    ]
