# Generated by Django 5.2.1 on 2025-05-17 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_client_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests_count',
            field=models.IntegerField(verbose_name='Кол-во гостей'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст'),
        ),
    ]
