# Generated by Django 5.2.1 on 2025-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_booking_guests_count_alter_client_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, default='media/rooms/default.jpeg', null=True, upload_to='media/rooms/', verbose_name='Фото номера'),
        ),
    ]
