# Generated by Django 5.2.1 on 2025-05-20 10:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_client_age_client_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2007, 5, 20))], verbose_name='Дата рождения'),
        ),
    ]
