# Generated by Django 5.2.1 on 2025-09-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_booking_status_alter_client_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, verbose_name='Текст сертификата'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('event', models.TextField(verbose_name='Событие')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='core.companyinfo')),
            ],
            options={
                'verbose_name': 'Историческое событие',
                'verbose_name_plural': 'Исторические события',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование реквизита')),
                ('value', models.TextField(verbose_name='Значение реквизита')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='core.companyinfo')),
            ],
            options={
                'verbose_name': 'Реквизит компании',
                'verbose_name_plural': 'Реквизиты компании',
                'ordering': ['order'],
            },
        ),
    ]
