# Generated by Django 5.2.1 on 2025-09-15 10:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_newsarticle_brief_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2007, 9, 15))], verbose_name='Дата рождения'),
        ),
    ]
