import random
from inputs import input_int_list

def generate_int_sequence(seq: list, size: int, min_val: int = -100, max_val: int = 100):
    """
    Initializes the provided list with a sequence of random integers generated by a generator function.
    Args:
        seq (list): The list to be initialized.
        size (int): The number of random integers to generate.
        min_val (int, optional): The minimum value for random integer generation. Defaults to -100.
        max_val (int, optional): The maximum value for random integer generation. Defaults to 100.
    """
    seq[:] = [random.randint(min_val, max_val) for _ in range(size)]


def user_input_init_sequence(seq: list, size: int):
    """
    Initializes the provided list with a sequence of integers entered by the user.
    Args:
        seq (list): The list to be initialized.
        size (int): The number of integers to input.
    Note:
        This function relies on the `input_int_list(size)` function to handle user input.
    """
    seq[:] = input_int_list(size)