# Generated by Django 5.2.1 on 2025-05-17 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_ages_client_age_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18, message='Возраст должен быть в пределах от 18 до 120')], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='формат белорусского номера: +375 (XX) XXX-XX-XX', regex='\\s*\\+375\\s*\\(\\d{2}\\)\\s*\\d{3}-\\d{2}-\\d{2}\\s*$')], verbose_name='Номер телефона'),
        ),
    ]
