# Generated by Django 5.2.1 on 2025-09-14 11:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_partner_alter_client_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Забронировано'), ('paid', 'Оплачено')], default='booked', max_length=10, verbose_name='Статус брони'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2007, 9, 14))], verbose_name='Дата рождения'),
        ),
    ]
