# Generated by Django 5.2.1 on 2025-09-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_newsarticle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='brief_content',
            field=models.TextField(default=models.CharField(max_length=100, verbose_name='Заголовок'), max_length=100, verbose_name='Краткое содержание'),
        ),
    ]
