# Generated by Django 5.2.1 on 2025-05-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=150, verbose_name='Ответ')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/news/', verbose_name='Картинка'),
        ),
    ]
