# Generated by Django 5.2.1 on 2025-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_amenity_category_alter_employeecontact_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ages',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='Возраст'),
        ),
    ]
