# Generated by Django 5.2.1 on 2025-05-17 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_room_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ages',
            new_name='age',
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=19, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +375 (XX) XXX-XX-XX', regex='\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Номер телефона'),
        ),
    ]
