# Generated by Django 5.2.1 on 2025-09-12 13:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_client_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='media/partners/', verbose_name='Логотип')),
                ('website', models.URLField(verbose_name='Сайт компании')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2007, 9, 12))], verbose_name='Дата рождения'),
        ),
    ]
