# Generated by Django 5.2.1 on 2025-09-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_companyinfo_certificate_text_companyinfo_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(max_length=1500, verbose_name='Новость'),
        ),
    ]
