# Generated by Django 5.2.1 on 2025-09-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_newsarticle_brief_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='brief_content',
            field=models.TextField(max_length=100, verbose_name='Краткое содержание'),
        ),
    ]
